export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  dashboard: "/dashboard",
  workshopRequests: "/app/requests",
  workshopRequestDetail: (requestId = ":requestId") => `/app/requests/${requestId}`,
  workshopQuotation: (requestId = ":requestId") => `/app/requests/${requestId}/quote`,
  workshopBuilds: "/app/builds",
  workshopBuildDetail: (projectId = ":projectId") => `/app/builds/${projectId}`,
  workshopHandover: "/app/handover",
  workshopHandoverDetail: (projectId = ":projectId") => `/app/handover/${projectId}`,
  appConfigurator: "/app/configurator",
  appSpecReview: "/app/spec-review",
  appQuotes: "/app/quotes",
  appOrderProgress: "/app/order-progress",
  configurator: "/configurator",
  specReview: "/spec-review",
  quotes: "/quotes",
}
